layout:
  dpi: 300
  x: 2.5
  y: 3.5
  font: OLDSH__

  fields:
    border:
      type: rounded
      x: 0
      y: 0
      sizex: 2.5
      sizey: 3.5
      cornerx: 0.15 
      cornery: 0.15
      color: border 

    background:
      type: icon
      x: 0.15
      y: 0.15
      sizex: 2.2
      sizey: 3.2
      crop: true
      image: base_background.png
      color: base
      combine: overlay
      z-index: 1

    background_overlay:
      type: aspect_icon
      x: 0.15
      y: 0.15
      sizex: 2.2
      sizey: 3.2
      crop: true
      images:
        c: colorless_overlay_spell.png 
        n: anger_overlay.png 
        a: apathy_overlay.png 
        e: entropy_overlay.png 
        g: greed_overlay.png 
        o: order_overlay.png 
        p: pride_overlay.png 
      color: base
      combine: overlay
      z-index: 2

    name:
      type: text
      x: 0.35
      y: 0.3
      sizex: 2.1
      color: text
      textsize: 0.2
      font: Livingst
      z-index: 3

    title:
      type: text
      x: 0.2
      y: 0.4
      sizex: 2.1
      color: text
      align: center
      z-index: 3

    class:
      type: text 
      x: 0.2
      y: 1.0
      sizex: 0.8
      color: text
      rotate: 270
      align: right
      z-index: 3

    chroma_ability:
      type: text 
      x: 0.3 
      y: 1.4
      sizex: 2.0
      color: text
      z-index: 3

    ability:
      type: text 
      x: 0.3
      y: 2.0
      sizex: 1.85
      sizey: 1.0
      color: text
      z-index: 3

    attack:
      type: text 
      x: 2.0
      y: 3.1
      sizex: 1.8
      color: text
      z-index: 3

    hp:
      type: text 
      x: 2.2
      y: 3.1
      sizex: 1.8
      color: text
      z-index: 3

    cost:
      type: text
      x: 0.2
      y: 0.5
      sizex: 1.8
      color: text
      z-index: 3

    units:
      type: text
      x: 0.2
      y: 3.1
      sizex: 1.8
      color: text
      z-index: 3
