cards:
  - name: "Terrezork, Oglin Instigator"
    copies: 1

  - name: "Malashk the Sacrificed"
    copies: 1

  - name: "Stormgear the Tempest"
    copies: 1

  - name: "Yaw, Harbinger of the Void"
    copies: 1

  - name: "Gerrick of the Legion"
    copies: 1

  - name: "Zzrech the Broodmaster"
    copies: 1
