cards:
  - name: "Terrezork"
    copies: 1

  - name: "Malashk"
    copies: 1

  - name: "Stormgear"
    copies: 1

  - name: "Yaw"
    copies: 1

  - name: "Gerrick"
    copies: 1

  - name: "Zzrech"
    copies: 1
