symbols:
  - symbol: "~"
    replace: name
    image: false
    fields:
      - ability_1
      - ability_2
      - ability_3
      - ability

  - symbol: "@"
    replace: title
    image: false
    fields:
      - ability_1
      - ability_2
      - ability_3
      - ability

  - symbol: "^"
    replace: hero
    image: false
    fields:
      - ability

  - symbol: "`c"
    replace: colorless_orb.png 
    image: true
    fields:
      - ability
      - ability_1
      - ability_2
      - ability_3

  - symbol: "`n"
    replace: anger_orb.png 
    image: true
    fields:
      - ability
      - ability_1
      - ability_2
      - ability_3

  - symbol: "`a"
    replace: apathy_orb.png 
    image: true
    fields:
      - ability
      - ability_1
      - ability_2
      - ability_3

  - symbol: "`e"
    replace: entropy_orb.png 
    image: true
    fields:
      - ability
      - ability_1
      - ability_2
      - ability_3

  - symbol: "`g"
    replace: greed_orb.png 
    image: true
    fields:
      - ability
      - ability_1
      - ability_2
      - ability_3

  - symbol: "`o"
    replace: order_orb.png 
    image: true
    fields:
      - ability
      - ability_1
      - ability_2
      - ability_3

  - symbol: "`p"
    replace: pride_orb.png 
    image: true
    fields:
      - ability
      - ability_1
      - ability_2
      - ability_3

  - symbol: "`v"
    replace: victory_point.png
    image: true
    fields:
      - ability
      - ability_1
      - ability_2
      - ability_3

  - symbol: "`h"
    replace: charge.png
    image: true
    fields:
      - ability
      - ability_1
      - ability_2
      - ability_3

  - symbol: "`l"
    replace: coin.png
    image: true
    fields:
      - ability
      - ability_1
      - ability_2
      - ability_3
