layout:
  dpi: 150
  x: 3
  y: 2.65
  font: OLDSH__

  fields:
    border:
      type: 6gon
      x: 0
      y: 0
      side: 1.5
      color: border
      round: 0.1

    background:
      type: icon
      x: 0.1
      y: 0.1
      sizex: 3
      sizey: 2.5
      side: 1.5
      color: base
      combine: 'overlay'
      poly-mask: 6
      image: base_background.png
      crop: true

    background_overlay:
      type: icon
      x: 0.1
      y: 0.1
      sizex: 3
      sizey: 2.5
      side: 1.5
      color: base
      combine: 'overlay'
      poly-mask: 6
      image: colorless_overlay.png
      crop: true

    name:
      type: text
      x: 0.4
      y: 0.2
      sizex: 0.7
      sizey: 0.14
      align: center
      color: text
      textsize: 0.14
      font: Livingst

    ability:
      type: text
      x: 0.25
      y: 0.6
      sizex: 1.1
      sizey: 0.45
      align: center
      color: text
      textsize: 0.11
