layout:
  dpi: 80
  x: 2.5
  y: 3.5

  fields:
    border:
      type: rounded
      x: 0
      y: 0
      sizex: 2.5
      sizey: 3.5
      cornerx: 0.15 
      cornery: 0.15
      color: border 

    background:
      type: rect
      x: 0.15
      y: 0.15
      sizex: 2.2
      sizey: 3.2
      color: base 

    name:
      type: text
      x: 0.2
      y: 0.25
      sizex: 2.1
      sizey: 0.2
      color: text

    title:
      type: text
      x: 0.2
      y: 0.4
      sizex: 2.1
      sizey: 0.2
      color: text

    class:
      type: text 
      x: 0.3 
      y: 0.8
      sizex: 0.2
      sizey: 2.1
      color: text
      rotate: 270

    chroma_ability:
      type: text 
      x: 0.3 
      y: 1.4
      sizex: 2.0
      sizey: 2.1
      color: text

    ability_1:
      type: text 
      x: 0.3 
      y: 1.5
      sizex: 1.8
      sizey: 2.1
      color: text
      
    ability_2:
      type: text 
      x: 0.3 
      y: ability_1.y
      sizex: 1.8
      sizey: 2.1
      color: text
    
    ability_3:
      type: text 
      x: 0.3 
      y: ability_2.y
      sizex: 1.8
      sizey: 2.1
      color: text

    ability:
      type: text
      x: 0.3
      y: 2.0
      sizex: 1.85
      sizey: 2.1
      color: text

    attack:
      type: text 
      x: 2.0
      y: 3.3
      sizex: 1.8
      sizey: 2.1
      color: text

    hp:
      type: text 
      x: 2.2
      y: 3.3
      sizex: 1.8
      sizey: 2.1
      color: text

    cost:
      type: text
      x: 0.2
      y: 0.5
      sizex: 1.8
      sizey: 2.1
      color: text

    units:
      type: text
      x: 1.7
      y: 3.3
      sizex: 1.8
      sizey: 2.1
      color: text

    equipment:
      type: text
      x: 0.5
      y: 3.2
      sizex: 1.0
      sizey: 2.1
      color: text
