cards:
#Anger

  - name: "Oglin"
    copies: 1

  - name: "Bloodraiser"
    copies: 1

  - name: "Berserker"
    copies: 1

  - name: "Slayer"
    copies: 1

  - name: "Magmaguana"
    copies: 1
    

#Apathy

  - name: "Megamite"
    copies: 1

  - name: "Technomancer"
    copies: 1

  - name: "Maer Guardian"
    copies: 1

  - name: "Nullifier"
    copies: 1

  - name: "Colossus"
    copies: 1

#Entropy    
  - name: "Turglid"
    copies: 1

  - name: "Void Knight"
    copies: 1

  - name: "Rift Raider"
    copies: 1

  - name: "Ythog"
    copies: 1

  - name: "Rift Trawler"
    copies: 1

#Greed    
  - name: "Zombie"
    copies: 1

  - name: "Gargoyle"
    copies: 1

  - name: "Acolyte"
    copies: 1

  - name: "Gorgon"
    copies: 1

  - name: "Flesh Golem"
    copies: 1

#Order
    
  - name: "Man at Arms"
    copies: 1

  - name: "Stormbow"
    copies: 1

  - name: "Cleric"
    copies: 1

  - name: "Iron Warden"
    copies: 1

  - name: "King's Guard"
    copies: 1

#Pride
    
  - name: "Spider Rider"
    copies: 1

  - name: "Redclaws"
    copies: 1

  - name: "Badger Druid"
    copies: 1

  - name: "Oglogasaur"
    copies: 1

  - name: "King of the Jungle"
    copies: 1

#The Laze    

  - name: "Revenant"
    copies: 2

  - name: "Tuskil"
    copies: 2

  - name: "Locust Shaman"
    copies: 1

  - name: "Corruptor"
    copies: 2

  - name: "Guard Tower"
    copies: 2

  - name: "Paladin"
    copies: 2    

  - name: "Static Field"
    copies: 1

  - name: "Auto-Salvager"
    copies: 1

  - name: "Soul Link"
    copies: 1

  - name: "Spiked Gauntlets"
    copies: 2

  - name: "Oath of the Undying"
    copies: 1

  - name: "Rending Claws"
    copies: 2

  - name: "Razor Hide"
    copies: 1

  - name: "Void Blade"
    copies: 1

  - name: "Cutter"
    copies: 1

  - name: "Chopper"
    copies: 1
  
  - name: "Soul Drinker"
    copies: 1
  
  - name: "Angel's Breath"
    copies: 1    

  - name: "Frenzy"
    copies: 2    

  - name: "Winds of War"
    copies: 1

  - name: "Warcry"
    copies: 2

  - name: "Life Drain"
    copies: 2

  - name: "Unearth"
    copies: 2
  
  - name: "Forbidden Knowledge"
    copies: 2
  
  - name: "Forced Evolution"
    copies: 2

  - name: "Accelerate"
    copies: 2
    
  - name: "Dimensional Break"
    copies: 1

  - name: "Aether Fuse"
    copies: 2

  - name: "Void Shift"
    copies: 2    

  - name: "Aberrate"
    copies: 2    
    
  - name: "Power Up"
    copies: 2

  - name: "Stoneform"
    copies: 2    

  - name: "Silence"
    copies: 2
    
  - name: "Shield Bash"
    copies: 2

  - name: "Hold the Line"
    copies: 2

  - name: "Combat Sanctions"
    copies: 2    
    
#Colorless
    
  - name: "Bastion"
    copies: 6

  - name: "Bounty Hunter"
    copies: 6

  - name: "Shifting Blade"
    copies: 12

  - name: "Dragon Plate"
    copies: 12

  - name: "Magic Missile"
    copies: 12

  - name: "Cultivate"
    copies: 12

  - name: "Warp Summon"
    copies: 12

  - name: "Block"
    copies: 12

  - name: "Aether Wings"
    copies: 12

  - name: "Runic Beacon"
    copies: 12

  - name: "Tectonic Shift"
    copies: 12

