layout:
  dpi: 150
  x: 3
  y: 2.65
  font: OLDSH__

  fields:
    border:
      type: 6gon
      x: 0
      y: 0
      side: 1.5
      color: border
      round: 0.1

    background:
      type: icon
      x: 0.15
      y: 0.15
      sizex: 2.85
      sizey: 2.35
      side: 1.35
      color: base
      combine: 'overlay'
      poly-mask: 6
      image: base_background.png
      crop: true

    background_overlay:
      type: icon
      x: 0.15
      y: 0.15
      sizex: 2.85
      sizey: 2.35
      side: 1.35
      color: base
      combine: 'overlay'
      poly-mask: 6
      image: terrain_overlay.png
      crop: true

    name:
      type: text
      x: 0.55
      y: 0.6
      sizex: 1.9
      sizey: 0.3
      align: center
      color: text
      textsize: 0.3
      font: Livingst

    ability:
      type: text
      x: 0.8
      y: 1
      sizex: 1.35
      sizey: 1.25
      align: center
      color: text
      textsize: 0.15
