layout:
  dpi: 300
  x: 5.0
  y: 3.5
  font: OLDSH__

  fields:
    border:
      type: rounded
      x: 0
      y: 0
      sizex: 5.0
      sizey: 3.5
      cornerx: 0.15 
      cornery: 0.15
      color: border 

    background:
      type: icon
      x: 0.15
      y: 0.15
      sizex: 4.7
      sizey: 3.2
      image: base_background.png
      color: base
      combine: overlay

    background_overlay:
      type: aspect_icon
      x: 0.15
      y: 0.15
      sizex: 4.7
      sizey: 3.2
      images:
        c: anger_overlay.png 
        n: anger_overlay.png 
        a: apathy_overlay.png 
        e: entropy_overlay.png 
        g: greed_overlay.png 
        o: order_overlay.png 
        p: pride_overlay.png 
      color: base
      combine: overlay

    name:
      type: text
      x: 1.5
      y: 0.3
      sizex: 2.1
      color: text
      textsize: 0.2
      font: Livingst

    title:
      type: text
      x: 0.2
      y: 0.4
      sizex: 2.1
      color: text
      textsize: 0.17
      align: center

    class:
      type: text 
      x: 0.2
      y: 1.0
      sizex: 0.8
      color: text
      rotate: 270
      align: right

    chroma_ability:
      type: text 
      x: 0.3 
      y: 1.4
      sizex: 2.0
      color: text
      textsize: 0.15

    ability_name_1:
      type: text
      x: 2.3
      y: 0.4
      sizex: 1.5
      sizey: 0.2
      color: text
      textsize: 0.15

    ability_tier_1:
      type: text
      x: 3.8
      y: 0.4
      sizex: 0.2
      sizey: 0.2
      color: text
      textsize: 0.15

    ability_1:
      type: text 
      x: 2.3 
      y: ability_name_1.y
      sizex: 2.3
      sizey: 1.4
      color: text

    ability_name_2:
      type: text
      x: 2.3
      y: ability_1.y
      sizex: 1.5
      sizey: 0.2
      color: text
      textsize: 0.15

    ability_tier_2:
      type: text
      x: 3.8
      y: ability_1.y
      sizex: 0.3
      sizey: 0.2
      color: text
      textsize: 0.15

    ability_2:
      type: text 
      x: 2.3 
      y: ability_name_2.y
      sizex: 2.3
      sizey: 1.4
      color: text

    ability_name_3:
      type: text
      x: 2.3
      y: ability_2.y
      sizex: 1.5
      sizey: 0.2
      color: text
      textsize: 0.15

    ability_tier_3:
      type: text
      x: 3.8
      y: ability_2.y
      sizex: 0.2
      sizey: 0.2
      color: text
      textsize: 0.15

    ability_3:
      type: text 
      x: 2.3
      y: ability_name_3.y
      sizex: 2.3
      sizey: 1.4
      color: text

    attack:
      type: text 
      x: 2.0
      y: 3.1
      sizex: 1.8
      color: text

    hp:
      type: text 
      x: 2.2
      y: 3.1
      sizex: 1.8
      color: text

    cost:
      type: text
      x: 0.2
      y: 0.5
      sizex: 1.8
      color: text

    units:
      type: text
      x: 0.2
      y: 3.3
      sizex: 1.8
      color: text
