globals:
  border: '#000'
  none: '#0000'

aspects:
  n:
    name: anger
    color:
      base: '#911'
      text: '#000'

  a:
    name: apathy
    color:
      base: '#777'
      text: '#000'

  e:
    name: entropy
    color:
      base: '#5f0055'
      text: '#FFF'

  g:
    name: greed
    color:
      base: '#333'
      text: '#FFF'

  o:
    name: order
    color:
      base: '#dfa232'
      text: '#000'

  p:
    name: pride
    color:
      base: '#005620'
      text: '#FFF'

  c:
    name: colorless
    color:
      base: '#CCC'
      text: '#444'
