symbols:
  - symbol: "~"
    replace: name
    field: true
    fields:
      - ability_1
      - ability_2
      - ability_3
      - ability

  - symbol: "@"
    replace: title
    field: true
    fields:
      - ability_1
      - ability_2
      - ability_3

  - symbol: "^"
    replace: hero
    field: true
    fields:
      - ability

  - symbol: "%"
    replace: SOTM
    field: false
    fields:
      - ability

  - symbol: "`o"
    replace: weapon
    field: false
    fields:
      - equipment

  - symbol: "`a"
    replace: ability
    field: false
    fields:
      - equipment

  - symbol: "`d"
    replace: armor
    field: false
    fields:
      - equipment
