symbols:
  - symbol: "~"
    replace: name
    image: false
    fields:
      - ability_1
      - ability_2
      - ability_3
      - ability

  - symbol: "@"
    replace: title
    image: false
    fields:
      - ability_1
      - ability_2
      - ability_3
      - ability

  - symbol: "^"
    replace: hero
    image: false
    fields:
      - ability

  - symbol: "%"
    replace: SOTM
    image: false
    fields:
      - ability

  - symbol: "`b"
    replace: weapon.png
    image: true
    fields:
      - ability
      - ability_1
      - ability_2
      - ability_3
